<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReportsTableSeeder extends Seeder
{
    public function run()
    {
        $reports = [
            [
                'id'           => 1,
                'report_title' => 'Number of Member without ID and List of Member',
                'query'        => 'SELECT __columns__ FROM persons WHERE `user_id` IS NULL;',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 2,
                'report_title' => 'Number of Member with ID and list of Members',
                'query'        => 'SELECT __columns__ FROM persons WHERE `user_id` IS NOT NULL;',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 3,
                'report_title' => 'Number of Orphan (Late Father & Late Mother) Member with List',
                'query'        => 'SELECT __columns__ FROM persons WHERE `father_is_dead` = 1 AND `mother_is_dead` = 1;',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 4,
                'report_title' => 'Number of Male (Child) with List depending on Age barrier below 7 years',
                'query'        => 'SELECT __columns__ FROM persons WHERE `gender` = "male" AND `dob` > DATE_SUB(NOW(), INTERVAL 7 YEAR);',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 5,
                'report_title' => 'Number of Female (Child) with List depending on Age barrier below 7 years',
                'query'        => 'SELECT __columns__ FROM persons WHERE `gender` = "female" AND `dob` > DATE_SUB(NOW(), INTERVAL 7 YEAR);',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 6,
                'report_title' => 'Number of Male (Child) with List depending on Age barrier more than 7 years and below 15 Years',
                'query'        => 'SELECT __columns__ FROM persons WHERE `gender` = "male" AND `dob` < DATE_SUB(NOW(), INTERVAL 7 YEAR) AND `dob` > DATE_SUB(NOW(), INTERVAL 15 YEAR);',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 7,
                'report_title' => 'Number of Female (Child) with List depending on Age barrier more than 7 years and below 15 Years',
                'query'        => 'SELECT __columns__ FROM persons WHERE `gender` = "female" AND `dob` < DATE_SUB(NOW(), INTERVAL 7 YEAR) AND `dob` > DATE_SUB(NOW(), INTERVAL 15 YEAR);',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 8,
                'report_title' => 'Number of Male (Young) with List depending on Age barrier more than 15 years and below 40 Years',
                'query'        => 'SELECT __columns__ FROM persons WHERE `gender` = "male" AND `dob` < DATE_SUB(NOW(), INTERVAL 15 YEAR) AND `dob` > DATE_SUB(NOW(), INTERVAL 40 YEAR);',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 9,
                'report_title' => 'Number of Female with List depending on Age barrier more than 15 years',
                'query'        => 'SELECT __columns__ FROM persons WHERE `gender` = "female" AND `dob` < DATE_SUB(NOW(), INTERVAL 15 YEAR);',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 10,
                'report_title' => 'Number of Male with List depending on Age barrier more than 40 and below 50 years',
                'query'        => 'SELECT __columns__ FROM persons WHERE `gender` = "male" AND `dob` < DATE_SUB(NOW(), INTERVAL 40 YEAR) AND `dob` > DATE_SUB(NOW(), INTERVAL 50 YEAR);',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 11,
                'report_title' => 'Number of Male with List depending on Age barrier more than 50',
                'query'        => 'SELECT __columns__ FROM persons WHERE `gender` = "male" AND `dob` < DATE_SUB(NOW(), INTERVAL 50 YEAR);',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 12,
                'report_title' => 'Number of Male with List depending on Age more than 60',
                'query'        => 'SELECT __columns__ FROM persons WHERE `gender` = "male" AND `dob` < DATE_SUB(NOW(), INTERVAL 60 YEAR);',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 13,
                'report_title' => 'Number of Male with List depending on Age barrier more than 40 years',
                'query'        => 'SELECT __columns__ FROM persons WHERE `gender` = "male" AND `dob` < DATE_SUB(NOW(), INTERVAL 40 YEAR);',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 14,
                'report_title' => 'Number of Members without Blood Group and the List',
                'query'        => 'SELECT __columns__ FROM persons WHERE `blood_group` IS NULL;',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 15,
                'report_title' => 'Number of Members with Blood Group and the List',
                'query'        => 'SELECT __columns__ FROM persons WHERE `blood_group` IS NOT NULL;',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 16,
                'report_title' => 'Individual Number of A+Ve, B+Ve, AB+Ve, O+Ve, A-Ve, B-Ve, AB-Ve, O-Ve Blood Group Holder and their individual List',
                'query'        => '',
                'status'       => 0,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 17,
                'report_title' => 'Member List with General Information',
                'query'        => '',
                'status'       => 0,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 18,
                'report_title' => 'Email Address Containing Member List',
                'query'        => 'SELECT __columns__ FROM persons WHERE `email` IS NOT NULL;',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 19,
                'report_title' => 'List of Unmarried Male (Young & Old) with Details',
                'query'        => 'SELECT __columns__ FROM persons WHERE `gender` = "male" and  `marital_status` = 0;',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 20,
                'report_title' => 'List of Married (Young & Old) with Details',
                'query'        => 'SELECT __columns__ FROM persons WHERE `gender` = "male" and  `marital_status` = 1;',
                'status'       => 1,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 21,
                'report_title' => 'Qualification wise member list with detail',
                'query'        => '',
                'status'       => 0,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 22,
                'report_title' => 'Institution wise member list',
                'query'        => '',
                'status'       => 0,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 23,
                'report_title' => 'Profession wise member list',
                'query'        => '',
                'status'       => 0,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id'           => 24,
                'report_title' => 'Company wise Member List',
                'query'        => '',
                'status'       => 0,
                'type'         => null,
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
        ];

        foreach ($reports as $report) {
            DB::table('reports')->insert($report);
        }
    }
}
